export enum NotificationType {
  'ADD_EMPLOYEE' = 'ADD_EMPLOYEE',
  'REMOVE_EMPLOYEE' = 'REMOVE_EMPLOYEE',
  'UPDATE_PROJECT_STATUS' = 'UPDATE_PROJECT_STATUS',
  'UPDATE_PROJECT_INFORMATION' = 'UPDATE_PROJECT_INFORMATION',
}
